# Generated by Django 6.1.1 on 2026-09-13 18:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_bookingrequest'),
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_number', models.CharField(max_length=50)),
                ('title', models.CharField(default='Photography Service Agreement', max_length=300)),
                ('terms', models.TextField(blank=True, help_text='Contract terms and conditions')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('signed', 'Signed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('client_signature', models.TextField(blank=True, help_text='Base64 encoded signature image')),
                ('client_signed_at', models.DateTimeField(blank=True, null=True)),
                ('studio_signature', models.TextField(blank=True)),
                ('studio_signed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='bookings.booking')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='studios.studio')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('studio', 'contract_number')},
            },
        ),
    ]
