# Generated by Django 6.1.1 on 2026-09-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_payment_booking_alter_payment_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
