# Generated by Django 6.1.1 on 2026-09-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('pos', 'POS'), ('card', 'Card'), ('online', 'Online Payment'), ('other', 'Other')], db_index=True, default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(db_index=True),
        ),
    ]
