# Generated by Django 6.1.1 on 2026-09-13 18:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_invoice_issue_date_alter_invoice_status_and_more'),
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_type', models.CharField(choices=[('seven_day', '7 Days Before'), ('three_day', '3 Days Before'), ('due_date', 'On Due Date'), ('overdue_7', '7 Days Overdue'), ('overdue_14', '14 Days Overdue'), ('overdue_30', '30 Days Overdue')], max_length=20)),
                ('sent_via', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Both')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='finance.invoice')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reminders', to='studios.studio')),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('invoice', 'reminder_type')},
            },
        ),
    ]
