# Generated by Django 5.1.15 on 2026-09-09 19:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('gallery', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album_type', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('pages', models.IntegerField(default=20)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('design_status', models.CharField(choices=[('pending', 'Pending Selection'), ('designing', 'Designing'), ('review', 'Internal Review'), ('client_approval', 'Client Approval'), ('production', 'Sent For Production'), ('received', 'Received'), ('qc', 'Quality Check'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('client_approved', models.BooleanField(default=False)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_orders', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FrameOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size', models.CharField(max_length=50)),
                ('frame_type', models.CharField(blank=True, max_length=100)),
                ('orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('internal_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('customer_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered'), ('received', 'Received'), ('qc', 'Quality Check'), ('ready', 'Ready'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_orders', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('print_size', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('paper_type', models.CharField(blank=True, max_length=100)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('internal_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('customer_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('sent', 'Sent to Printer'), ('printing', 'Printing'), ('qc', 'Quality Check'), ('ready', 'Ready'), ('delivered', 'Delivered'), ('reprint', 'Reprint Required')], default='pending', max_length=20)),
                ('requested_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='clients.client')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='gallery.photo')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='projects.project')),
            ],
            options={
                'ordering': ['-requested_date'],
            },
        ),
    ]
