# Generated by Django 6.1.1 on 2026-09-13 09:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0001_initial'),
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintPriceList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_type', models.CharField(choices=[('print', 'Print'), ('frame', 'Frame'), ('album', 'Album')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('paper_type', models.CharField(blank=True, max_length=100)),
                ('internal_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_prices', to='studios.studio')),
            ],
            options={
                'ordering': ['product_type', 'sort_order', 'name'],
                'abstract': False,
            },
        ),
    ]
