# Generated by Django 5.1.15 on 2026-09-09 19:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('deposit_percentage', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('duration_hours', models.DecimalField(decimal_places=1, default=1, max_digits=5)),
                ('outfit_changes', models.IntegerField(default=1)),
                ('edited_images', models.IntegerField(default=10)),
                ('prints_included', models.IntegerField(default=0)),
                ('print_sizes', models.JSONField(blank=True, default=list)),
                ('frames_included', models.IntegerField(default=0)),
                ('frame_sizes', models.JSONField(blank=True, default=list)),
                ('album_included', models.BooleanField(default=False)),
                ('album_specification', models.CharField(blank=True, max_length=200)),
                ('digital_files_included', models.BooleanField(default=True)),
                ('delivery_estimate_days', models.IntegerField(default=14)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('extra_image_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='studios.studio')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PackageAddon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.TextField(blank=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='packages.package')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_categories', to='studios.studio')),
            ],
            options={
                'verbose_name_plural': 'Service categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='package',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='packages.servicecategory'),
        ),
    ]
