# Generated by Django 5.1.15 on 2026-09-09 19:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('studios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('next_follow_up', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('follow_up', 'Follow-up'), ('quotation_sent', 'Quotation Sent'), ('negotiating', 'Negotiating'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('converted_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_leads', to='clients.client')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='studios.studio')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
