# Generated by Django 6.1.1 on 2026-09-11 23:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clients', '0002_communication'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portal_user', to='clients.client')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this client user belongs to.', related_name='portal_clientuser_set', related_query_name='portal_clientuser', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this client user.', related_name='portal_clientuser_set', related_query_name='portal_clientuser', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Client User',
                'verbose_name_plural': 'Client Users',
            },
        ),
    ]
