# Generated by Django 6.1.1 on 2026-09-13 18:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_bookingrequest'),
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(max_length=300)),
                ('client_email', models.EmailField(max_length=254)),
                ('nps_score', models.IntegerField(blank=True, help_text='0-10 NPS score', null=True)),
                ('overall_rating', models.IntegerField(blank=True, help_text='1-5 stars', null=True)),
                ('quality_rating', models.IntegerField(blank=True, null=True)),
                ('service_rating', models.IntegerField(blank=True, null=True)),
                ('value_rating', models.IntegerField(blank=True, null=True)),
                ('would_recommend', models.BooleanField(blank=True, null=True)),
                ('feedback_text', models.TextField(blank=True)),
                ('improvements', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='bookings.booking')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='studios.studio')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
