# Generated by Django 5.1.15 on 2026-09-09 19:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_selection', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=500)),
                ('original_file_name', models.CharField(blank=True, max_length=500)),
                ('storage_key', models.CharField(max_length=1000)),
                ('thumbnail_key', models.CharField(blank=True, max_length=1000)),
                ('preview_key', models.CharField(blank=True, max_length=1000)),
                ('image_number', models.IntegerField(default=0)),
                ('capture_date', models.DateTimeField(blank=True, null=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gallery.gallery')),
            ],
            options={
                'ordering': ['image_number'],
            },
        ),
        migrations.CreateModel(
            name='PhotoSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_favourite', models.BooleanField(default=False)),
                ('finalized', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_selections', to='clients.client')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='gallery.photo')),
            ],
            options={
                'unique_together': {('photo', 'client')},
            },
        ),
    ]
