# Generated by Django 6.1.1 on 2026-09-12 20:01

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_fde', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgechunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
