# Generated by Django 6.1.1 on 2026-09-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_reminder', 'Booking Reminder'), ('deposit_due', 'Deposit Due'), ('delivery_due', 'Delivery Due'), ('selection_ready', 'Selection Ready'), ('editing_complete', 'Editing Complete'), ('print_ready', 'Print Ready'), ('low_stock', 'Low Stock'), ('maintenance_due', 'Maintenance Due'), ('payment_received', 'Payment Received'), ('general', 'General')], db_index=True, default='general', max_length=30),
        ),
    ]
